name: Keep Render Awake

on:
  schedule:
    - cron: "*/13 * * * *" # every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping service
        run: |
          curl -m 10 https://mental-blogger.onrender.com/ || true

